// Command engine-driver is a standalone CL mock that drives the engine
// API of a running execution-layer client (besu / nethermind / reth)
// in dev mode. Wraps internal/engineapi.EngineDriver.
//
// Usage:
//
//	engine-driver \
//	  -engine http://127.0.0.1:8551 \
//	  -eth http://127.0.0.1:8545 \
//	  -fork osaka \
//	  -block-time 1s \
//	  -jwt-secret /path/to/jwt.hex   # optional; reth requires it
//
// Runs DriveLoop until SIGINT/SIGTERM. JWT is OPTIONAL: pass -jwt-secret
// for reth (which requires --authrpc.jwtsecret); omit for besu/nethermind
// which we boot with --engine-jwt-disabled.
package main

import (
	"context"
	"encoding/hex"
	"errors"
	"flag"
	"log"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/nerolation/state-actor/internal/engineapi"
)

func main() {
	engineURL := flag.String("engine", "http://127.0.0.1:8551", "engine API URL")
	ethURL := flag.String("eth", "http://127.0.0.1:8545", "JSON-RPC URL")
	fork := flag.String("fork", "osaka", "engine method version: cancun | prague | osaka")
	blockTime := flag.Duration("block-time", time.Second, "slot duration")
	jwtFile := flag.String("jwt-secret", "", "path to engine-API JWT secret file (64 hex chars); empty = no auth")
	flag.Parse()

	var jwtSecret []byte
	if *jwtFile != "" {
		raw, err := os.ReadFile(*jwtFile)
		if err != nil {
			log.Fatalf("read jwt-secret %s: %v", *jwtFile, err)
		}
		s := strings.TrimSpace(string(raw))
		// Tolerate a 0x prefix in case the file was generated by tooling
		// that adds one (foundry / some CL specs).
		s = strings.TrimPrefix(s, "0x")
		jwtSecret, err = hex.DecodeString(s)
		if err != nil {
			log.Fatalf("decode jwt-secret %s (want 64 hex chars): %v", *jwtFile, err)
		}
		if len(jwtSecret) != 32 {
			log.Fatalf("jwt-secret %s decoded to %d bytes, want 32", *jwtFile, len(jwtSecret))
		}
	}

	driver := &engineapi.EngineDriver{
		EngineURL: *engineURL,
		EthRPCURL: *ethURL,
		BlockTime: *blockTime,
		Fork:      engineapi.Fork(*fork),
		JWTSecret: jwtSecret,
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sig
		log.Printf("signal received, shutting down driver")
		cancel()
	}()

	log.Printf("engine-driver: engine=%s eth=%s fork=%s block-time=%s",
		*engineURL, *ethURL, *fork, *blockTime)
	if err := driver.DriveLoop(ctx); err != nil && !errors.Is(err, context.Canceled) {
		log.Fatalf("driver exited with error: %v", err)
	}
	log.Printf("driver shut down cleanly")
}
